proja/urls.py
from django.contrib import admin
from django.urls import path

from infoa import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('infoa/<int:emp_id>/',views.emp_detail, name='emp_detail'),
    path('about/',views.about, name='about'),
]

infoa/models.py
from django.db import models

# Create your models here.
# Creating our class to cotain the required information for/about each employee
class Employee(models.Model):
    # first field for saving the first name
    first = models.CharField(max_length=40)
    # last field for saving the last name
    last = models.CharField(max_length=40)
    GENDER_CHOICES = [('M','Male'),('F','Female')]
    gender = models.CharField("Gender",max_length=1, choices=GENDER_CHOICES, blank=True)
    start_date = models.DateField("Start Date", blank=True)
    end_date = models.DateField("End Date", blank=True, null=True)
    phone = models.CharField("Phone Number", max_length=12, blank=True)
    email = models.EmailField("Email", max_length=30, null=True, unique= True)
    EMP_TYPE = [("P","Part Time"),("F","Full TIme")]
    emp_type = models.CharField("Employment Type",max_length=1, choices=EMP_TYPE, blank=True)
    dept = models.CharField("Department",max_length=20, blank=True)
    position = models.CharField("Position",max_length=40, blank=True)
    benefits = models.ManyToManyField("Benefit", blank=True)
    
    def __str__(self):
        return (f"{self.first} {self.last}")


class Benefit(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

infoa/views.py
# the render module will be used to render our html templates
from django.shortcuts import render
# Create your views here.
from .models import Employee
from django.http import Http404

# Any html page (template) you want to display/render has to have its own function defined in this file "views.py":

# starting with the first page "home page"
# def home ==> for the home page
# As a rule, every view function below has to have an argument called "request"
def home(request): # it takes a "request" as an argument, we can set the parameter as request
    # render(request: HttpRequest, template_name, { could be empty OR anything we want to pass to this page } )
    # { }
    # { 'feild1': numeric_value, 'feild2': 'text_value', 'field3': variable_name }
    employees = Employee.objects.all()
    return render(request,'home.html',{'employees':employees})

# def emp_detail ==> for the employee detail page
# this function requires the emp_id as a second parameter
def emp_detail(request, emp_id):
    try:
        employee = Employee.objects.get(id=emp_id)
    except Employee.DoesNotExist:
        raise Http404('Sorry, Employee not found!')
    return render(request,'emp_detail.html',{'employee':employee})

# def about ==> for the about the project page
# about function has the required argument "request" and so on for all the functions
def about(request):
    return render(request,'about.html')

infoa/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    About this project
{% endblock %}

{% block content %}

<div>
    <img src="{% static 'images/bg3.jpg' %}" class="callout-container2 bkg" alt="About Image"> 
    <div class="centered h1">About this project</div> 
</div> 
<div class="content1">
    <h2>Introduction</h2>
    <br>
    <p>This project is to design a website to display records from Django models using test data.</p> 
    <p>The Home page displays a list of staff records.  When the name is selected, it shows the details for any records selected from the home page.</p>
</div>


<div class="content1">
    <h2>Features</h2>
    <br>
    <p>On the homepage, it shows the summary of staff appointment.  The data is preset in database.</p> 
    <p>When the url of name is selected, it will direct to other page which will display the staff info.</p> 
    <br>
</div>

<div class="content1">
    <h2>Technologies used in web development</h2>
    <br>
    <ul>
        <li>HTML5</li>
        <li>CSS3</li>
        <li>Bootstrap</li>
        <li>Jquery</li>
        <li>Javascript</li>
        <li>Python</li>
        <li>Django</li>
    </ul>
</div>


{% endblock %}

infoa/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> 
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-fluid navalert-container">
        <nav class="navbar navbar-dark navbar-expand-sm">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>  
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mr-2"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item mr-2"><a class="nav-link" href="{% url 'about' %}">About this project</a></li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <footer>
        <ul class="social-networks">
          <li><a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a></li>   
          <li><a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter-square"></i></a></li>  
          <li><a href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a></li>  
       </ul> 
   </footer>
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
</body>
</html>

infoa/templates/emp_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Staff Info
{% endblock %}
{% block content %}

<div>
    <img src="{% static 'images/bg2.jpg' %}" class="callout-container1 bkg" alt="Info Image"> 
    <div class="centered h1">Staff Info</div> 
</div> 

<div class='container fmdesc'>
    <br>
    <h3 class='subhd1'>{{employee.first | capfirst}} {{employee.last | capfirst}} - ID#: {{ employee.id }}</h3>
    <br>
    <p><strong>Gender: </strong>{{ employee.gender }}</p>
    <p><strong>Phone Number: </strong>{{employee.phone}}</p>
    <p><strong>Email: </strong>{{employee.email}}</p>
    <p><strong>Department: </strong> {{ employee.dept | capfirst }}</p>
    <p><strong>Start Date: </strong>{{employee.start_date}}</p>
    {% if employee.end_date %}
    <p><strong>End Date: </strong> {{ employee.end_date}}</p>
    {% endif %}
    <p><strong>Employment Type: </strong> {{ employee.get_emp_type_display | capfirst }}</p>
    <p><strong>Position: </strong> {{ employee.position | capfirst }}</p>
    {% if employee.benefits.all %}
     <p><strong>Benefits Coverage:</strong></p>
     <ul>
     {% for item in employee.benefits.all %}
        <li>{{ item }}</li>            
     {% endfor %}
    </ul>
    {% endif %}
</div>

    
{% endblock content %}

infoa/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Staff Appointment
{% endblock title %}

{% block content %}

<div>
    <img src="{% static 'images/bg1.jpg' %}" class="callout-container bkg" alt="Home Image"> 
    <div class="centered h1">Staff Appointment</div> 
</div>    

{% for emp in employees %}
<div class='container fmdesc'> 
    <h3><a href="{% url 'emp_detail' emp.id %}">{{ emp.first | capfirst }} {{ emp.last | capfirst }} - ID#: {{ emp.id }}</a></h3>
    <br>
    <!-- Adding a few details for each staff-->
    <p><strong>Start Date: </strong>{{emp.start_date}}</p>
    {% if emp.end_date %}
    <p><strong>End Date: </strong> {{ emp.end_date}}</p>
    {% endif %}
    <p><strong>Employment Type: </strong> {{ emp.get_emp_type_display | capfirst }}</p>
    <p><strong>Position: </strong> {{ emp.position | capfirst }}</p>
</div>
{% endfor %}
{% endblock content %}